/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AccountGroupDto (
  id: Option[Int],
  /* 账户组名称 */
  displayName: Option[String],
  /* 是否是默认组 */
  isDefault: Option[Boolean],
  /* 是否静态（系统生成），不可删除 */
  isStatic: Option[Boolean]
) extends ApiModel


