/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AppDto (
  id: Option[Int],
  displayName: Option[String],
  appKey: Option[String],
  appEditionType: Option[AppEditionType],
  status: Option[AppStatus],
  /* 基础功能 */
  basic: Option[Boolean],
  /* 基础功能预期时间 */
  basicExpiryTime: Option[Double],
  /* 付费功能 */
  pay: Option[Boolean],
  /* 付费功能预期时间 */
  payExpiryTime: Option[Double]
) extends ApiModel


