/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AuthenticateModel (
  tenantCode: Option[String],
  /* 用户名 */
  userName: String,
  password: String,
  rememberClient: Option[Boolean],
  /* 未登录时访问的页面，登录后需要重定向 */
  returnUrl: Option[String]
) extends ApiModel


