/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AuthenticateResultModel (
  /* 授权Token */
  accessToken: Option[String],
  /* 有效时长 */
  expireInSeconds: Option[Int],
  /* 是否需要重置密码 */
  shouldResetPassword: Option[Boolean],
  /* 如果需要重置密码，生成ResetCode后返回前端 */
  passwordResetCode: Option[String],
  userId: Option[Long],
  returnUrl: Option[String]
) extends ApiModel


