/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class FilterTenantsDto (
  filter: Option[String],
  tenantCode: Option[String],
  tenantName: Option[String],
  appId: Option[Int],
  createDateStart: Option[Long],
  createDateEnd: Option[Long],
  pageIndex: Option[Int],
  pageSize: Option[Int]
) extends ApiModel


