/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class FilterAuditLogsDto (
  /* 创建时间从 */
  createTimeFrom: Option[Long],
  /* 创建时间到 */
  createTimeEnd: Option[Long],
  timeOfDurationFrom: Option[Int],
  timeOfDurationEnd: Option[Int],
  status: Option[String],
  account: Option[String]
) extends ApiModel


