/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PermissionDto (
  id: Option[Int],
  level: Option[Int],
  parentId: Option[Int],
  displayName: Option[String],
  desc: Option[String]
) extends ApiModel


